### PR TITLE
image height improvement

### PR DESCRIPTION
**Pull request by trba1810**
I'm not quite sure is this what you wanted,if it's not give me more info.

### CODE REVIEW

**Review by anicmarko9 — COMMENTED** [review]
I can't really see the difference. Everything is the same as it was, or am I missing something?

**Comment by trba1810** [comment]
You can do right click inspect and drag line to 1024px and see changes all the way down.

**Comment by anicmarko9** [comment]
I wanted image to fit from top to bottom the same way the whole text on the left side fits, same height. So everything below 1024px shouldn't matter, since it's collapsing into flex-col. Try adjusting 1024px+++ sizes.

**Comment by anicmarko9** [comment]
image

@trba1810 something in these borders.

**Comment by trba1810** [comment]
I've added some improvements,but it's not perfect alignment

**Comment by anicmarko9** [comment]
It's aligned closely enough, thanks for your contribution. Below 1280px is bad, but don't worry, I'll fix that when I get a chance.

**Pull request merged**
