### PR TITLE
[Fix] : Fixed the issue of responsive design

### LINKED ISSUE #235: [Bug]: The Home section is not responsive.
Describe the bug
-The icon on the home page is colliding with text and also the navbar is colliding with offer section also.
To Reproduce
-Go to 'Home Page'
-set 14 inch laptop dimensions [Width: 12.20 inches / 30.99 cm. Height: 6.86 inches / 17.43 cm.].
-see the err
-The icon at home page is colliding with text and also offer section also collides.

Screenshot

Screenshot 2023-09-14 124427

Expected Behaviour
-The website should be responsive . 
-the icon and the navbar do not collide with text and the offer section

### PR DESCRIPTION
**Pull request by Rohit-Sharmaa**
# Description
This pr fixes the issue of responsive design of the website 
Fixes #235

### CODE REVIEW

**Review by anicmarko9 — COMMENTED** [review]
Thanks for your contribution, but please don't push changes to the package-lock.json file. Just push the changed you made. Does it make sense to have +35000 and -35000 changes for one class name change? I'll merge once you revert changes to the package file, and also please remove the rgba class, since I don't want opacity to be 80%.

**Comment by Rohit-Sharmaa** [comment]
@anicmarko9 yes i will.

**Comment by anicmarko9** [comment]
If you are having hard time reverting this commit, you can start from the scratch by making another PR where you only add `sticky` tag and nothing else. That will also count as a contribution.

**Comment by Rohit-Sharmaa** [comment]
@anicmarko9 I did that . Please check my pr #237

**Pull request closed without merging**
