### PR TITLE
My attempt at changing the colors on hover. Any suggestions/improveme…

### PR DESCRIPTION
**Pull request by sujatrobhadra**
…nts would be highly recommended

### CODE REVIEW

**Review by anicmarko9 — COMMENTED** [review]
Please run `npm run format` in your terminal before pushing your code to this branch. I have no idea what have you added, changed or removed, you re-formatted the whole code.

Make another commit where the `index.css` file is formatted, that way I can see the changes you've made.

**Comment by sujatrobhadra** [comment]
I think it is correctly formatted now?

**Review by anicmarko9 — COMMENTED** [review]
You can test this code by running `npm run start`. You can see that is not really appealing to the eyes, I'm not sure if you saw your change. Here is how it should finally be looking like:
```ts
.popUpAnimation {
    @apply transition delay-150 duration-300 ease-in-out hover:-translate-y-1 hover:scale-110 hover:cursor-pointer hover:bg-secondary hover:text-white sm:space-y-6;
  }
.popUpAnimation:hover
    > .statIconAndTitleContainer
    > .statNumber
    > .statPlusIcon
    > svg {
    @apply fill-white opacity-100;
  }
  .statCard:hover > .statIconAndTitleContainer > div > svg {
    @apply opacity-100 text-white;
  }
// more lines of code...
.statIconSize {
    @apply text-2xl lg:text-3xl xl:text-4xl transition delay-150 duration-300 ease-in-out;
  }
  .plusIcon {
    @apply h-full opacity-30 transition delay-150 duration-300 ease-in-out;
  }
```
You can add this to your current change and see if it is good looking on hover effect. The only problem is that `+` sign is delayed, I don't know how to fix that.

**Comment by sujatrobhadra** [comment]
I did the color changes and tried to fix the issue of delay. If this doesn't feel right, I will try to set a custom delay in the config.

**Comment by sujatrobhadra** [comment]
Added a custom delay.

**Review by anicmarko9 — APPROVED** [review]
Looks good from coding perspective, I'll see if it makes sense once it goes into production. Thanks for your contribution, feel free to create issues, or pull requests if you notice that something is wrong with this project.

**Pull request merged**
