### PR TITLE
UI Improvements

### PR DESCRIPTION
**Pull request by anubhav1206**
Made some changes in the UI:
1. Added background and hover effect on navlinks
2. Added hover effect on statCards
3. Added hover effect on the contentThree component

### CODE REVIEW

**Review by anicmarko9 — CHANGES_REQUESTED** [review]
You are repeating this code a lot:
```tsc
sm:space-y-6 transition ease-in-out delay-150 hover:-translate-y-1 hover:text-white hover:scale-110 hover:bg-indigo-500 duration-300 hover:cursor-pointer
```

Put it inside of index.css and call it from there. Just like "statCard" is inside of index.css, you need to create another class "hoverNav" or some other name, and call it everywhere in the JSX components.

**Review by anicmarko9 — APPROVED** [review]
For some reason your most recent commit is not showing in this PR. It's probably a GitHub issue, I will try to resolve it somehow.

**Comment by anubhav1206** [comment]
> For some reason your most recent commit is not showing in this PR. It's probably a GitHub issue, I will try to resolve it somehow.

Whats the status as of now?

**Comment by anicmarko9** [comment]
I think that I see second commit, I will try to merge it. Thanks for the help, but if you have extra time on your hands, make sure to switch from snake_case to camelCase for the nameOfTheStyle.

**Comment by anubhav1206** [comment]
> I think that I see second commit, I will try to merge it. Thanks for the help, but if you have extra time on your hands, make sure to switch from snake_case to camelCase for the nameOfTheStyle.

done!

**Pull request merged**
