### PR TITLE
About us page update

### PR DESCRIPTION
**Pull request by Fernandojbf123**
Hello again my friend,

Added a new component and store it /components/AboutUs to keep maintainability.

Fixed semantic issues <figcaption> instead of <p>

I used npm run built and showed no errors as well as npm run start.

built_ok
npm run start

I hope it compliles this time.

Best,
Fernando

### CODE REVIEW

**Comment by Fernandojbf123** [comment]
I see it keeps failing the checks... 
Error

This is the error... Maybe should I rebuild the hole AboutUs page?
It could be that the route did not updated when I changed name from Aboutus to AboutUs...

Regards,
Fernando

**Review by anicmarko9 — COMMENTED** [review]
Looks good, I will look into that issue with `npm run build` and debug it.

**Comment by anicmarko9** [comment]
> Looks good, I will look into that issue with `npm run build` and debug it.

Looks like you forgot to rename file from Aboutus.tsx to AboutUs.tsx. It's all good though, now it works. Thanks again for the contribution.

**Comment by Fernandojbf123** [comment]
Glad I can contribute in this project and thank you for the coaching my friend, I really apreciate it! 😄

**Pull request merged**
